# Generated by Django 4.1.3 on 2022-11-13 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mahsulot_nomi', models.CharField(max_length=256)),
                ('Shifr', models.CharField(max_length=128)),
                ('Sinf', models.CharField(choices=[('I-sinf', 'I-sinf'), ('II-sinf', 'II-sinf'), ('III-sinf', 'III-sinf'), ('IV-sinf', 'IV-sinf'), ('V-sinf', 'V-sinf')], max_length=30)),
                ('Texnik_shart_seriyasi', models.CharField(max_length=16)),
                ('Texnik_shart_raqami', models.CharField(max_length=32)),
                ('Sana', models.DateTimeField(default=datetime.datetime(2022, 11, 13, 21, 51, 30, 86141))),
                ('Sinov_namunasi', models.BooleanField(default=False)),
                ('Partiya_soni_belgilash', models.IntegerField()),
                ('Partiya_raqami', models.IntegerField()),
                ('Buyurtmachi_nomi', models.CharField(max_length=128)),
                ('Buyurtmachi_raqami', models.IntegerField()),
                ('Buyurtma_soni', models.IntegerField()),
                ('Buyurtma_muddati', models.DateTimeField()),
                ('Sinov_bayonnomasi_raqami', models.CharField(max_length=8)),
                ('Sinov_bayonnomasi_sanasi', models.DateTimeField()),
                ('Sinov_qilingan_mahsulot_nomi', models.CharField(max_length=128)),
                ('Sinov_bayonnomasi_registratsiya_raqami', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.DeleteModel(
            name='products',
        ),
    ]
