# Generated by Django 4.1.3 on 2022-11-14 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app_1', '0002_product_delete_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Texnik_shart_seriyasi',
        ),
        migrations.AddField(
            model_name='product',
            name='Texnik_shart',
            field=models.CharField(default='TS-28078417', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='Sana',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 9, 31, 15, 240312)),
        ),
    ]
